spring.application.name=brt-backend

# Configuração da conexão com o MySQL
spring.datasource.url=jdbc:mysql://basedadosdai.mysql.database.azure.com:3306/brt_database?useSSL=true&serverTimezone=UTC
spring.datasource.username=administrador
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialeto do Hibernate (ajuda na comunicação com o MySQL)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Estratégia para criar tabelas automaticamente (Pode mudar depois)
spring.jpa.hibernate.ddl-auto=update    